version: "2.3"

volumes:
  pgdata:
  imposm:

networks:
  postgres_conn:
    driver: bridge
  web_conn:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:13-3.0
    command: postgres -c jit=off
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_conn

  imposm:
    build:
      context: imposm
    restart: always
    working_dir: /code
    env_file: .env
    volumes:
      - imposm:/imposm
      - ./imposm:/config
      - ./data:/data
    depends_on:
      - postgres
    networks:
      - postgres_conn

  pg_tileserv:
    image: pramsey/pg_tileserv
    env_file: .env
    depends_on:
      - postgres
    networks:
      - postgres_conn
      - web_conn

  front:
    image: node:12
    working_dir: /code
    command: yarn dev
    env_file: .env
    volumes:
      - ./front:/code
    depends_on:
      - pg_tileserv
    networks:
      - web_conn

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - pg_tileserv
    ports:
      - "3000:80"
    networks:
      - web_conn
