#!/bin/sh

export $(cat .env)

CONNECTION=$(echo $DATABASE_URL | sed -e 's/postgresql:/postgis:/g')

wget --output-document /data/data.pbf https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-latest.osm.pbf
docker-compose run --rm postgres psql $DATABASE_URL -c "CREATE EXTENSION IF NOT EXISTS hstore"
docker-compose run --rm imposm import -read /data/data.pbf -write -diff -optimize -deployproduction -config /config/config.json -connection $CONNECTION -overwritecache
docker-compose run --rm postgres psql $DATABASE_URL < view.sql
