// SELECT ?itemLabel
// WHERE
// {
//   ?item wdt:P31 wd:Q29044175.
//   SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
// }

export default [
  "Canyon Bicycles", "Cycles Peugeot", "Kettler", "Cube", "Rudge-Whitworth", "Look", "Gazelle", "Merida Bikes", "Colnago", "SCOTT Sports", "BMC Trading", "Cilo", "Giant", "August Rabeneick GmbH", "Riese & Müller", "Sparta B.V.", "Bianchi Bicycles", "Victoria", "Sachsenring Bike Manufaktur GmbH", "Diamant", "Brompton Bicycle", "Cannondale Bicycle Corporation", "Cervélo", "Trek", "Flandria", "Pinarello", "VSF Fahrradmanufaktur", "Orbea", "Felt Bicycles", "Focus Bikes", "Gudereit", "HP Velotechnik", "Den Beste Sykkel", "Moulton Bicycle", "Santa Cruz Bicycles", "Morita Miyata Corporation", "Eddy Merckx Cycles", "Norco Performance Bikes", "Velomobiel", "KhVZ", "Caloi", "Dorel Industries", "Falcon Cycles", "VanMoof", "Orange Mountain Bikes", "Pashley Cycles", "Serotta", "Surly", "Urago", "P.T. Helleberg", "Priority Bicycles", "Paper Bicycle", "Phizackerley", "Carl Heinrich Forcke", "Grundner & Lemisch", "Stromer",
"AddBike",
"Argo",
"Babboe",
"Bakfiets",
"BAYK",
"Benno",
"Bergamont",
"Bicicapace",
"Bike43",
"Bike Friday",
"Biomega",
"Bogbi",
"Bunch",
"Burley",
"Butchers & Bicycles",
"Ca Go",
"Carla Cargo",
"Carqon",
"CERO",
"chike",
"Christiana Bikes",
"Convercycle",
"Cube",
"Cycles Semaphore",
"Dolly",
"Douze",
"Elian",
"FlexiModal",
"Gleam",
"Hercules",
"Johny Loco",
"Joker",
"Kiffy",
"K-Ryole",
"Larry vs Harry",
"Le Petit Porteur",
"Mastretta",
"Monark",
"Mo-Tech",
"Muli",
"Nihola",
"Oklö",
"Omnium Cargo",
"Portal",
"Rad Power Bikes",
"Ridgeback",
"Riese & Müller",
"Stork",
"Taga",
"Tern",
"TRego",
"Tribe Bikes",
"Urban Arrow",
"Velove",
"VUF Bikes",
"Winther Bikes",
"workcycles",
"Xtracycle",
"XYZ Cargo",
"Yuba",
];
